name: texlo

services:
  valkey:
    image: valkey/valkey:latest
    container_name: texlo-valkey
    volumes:
      - ../docker/texlo/valkey:/data
    ports:
      - 6370:6379
    restart: unless-stopped
    networks:
      - texlo

networks:
  texlo:
    driver: bridge
